services:
  - type: web
    name: queroassistir-backend
    runtime: docker
    plan: free
    branch: main
    autoDeployTrigger: commit
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: TMDB_API_KEY
        sync: false
      - key: CORS_ALLOWED_ORIGIN_PATTERNS
        sync: false
